#!/bin/sh

PYTHONPATH="`dirname $0`:$PYTHONPATH"

if [ $# -ne 0 ]; then
    echo "Testing $1..."
    python "test/test_$1.py"
else
    echo "Testing squash..."
    python "test/test_squash.py"

    echo "Testing listparse..."
    python "test/test_listparse.py"

    echo "Testing spellnum..."
    python "test/test_spellnum.py"
fi
